---
- name: Setup sysctl for IPv4 Forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_file: "{{ item.key }}/etc/sysctl.conf"
    reload: no
  when: usb0_interface_cidr | length > 0
  loop: "{{ root_volume | dict2items }}"
  loop_control:
    label: "{{ item.value }}"

- name: Setup sysctl for IPv6 Forwarding
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    sysctl_file: "{{ item.key }}/etc/sysctl.conf"
    reload: no
  when: usb0_interface_cidr6 | length > 0
  loop: "{{ root_volume | dict2items }}"
  loop_control:
    label: "{{ item.value }}"

- name: Configure Packages to install on next boot
  become: true
  lineinfile:
    line: "iptables-persistent"
    path: "{{ item.key }}/root/packages"
    owner: "0"
    group: "0"
    mode: "0600"
    create: yes
  loop: "{{ root_volume | dict2items }}"
  loop_control:
    label: "{{ item.value }}"

- name: Make IPTables Rules directory
  file:
    path: "{{ item.key }}/etc/iptables"
    state: directory
    owner: "0"
    group: "0"
    mode: "0755"
  loop: "{{ root_volume | dict2items }}"
  loop_control:
    label: "{{ item.value }}"

# Rules based on https://tldp.org/HOWTO/html_single/Masquerading-Simple-HOWTO/
- name: Setup IPTables Rules
  template:
    src: rules.v4.j2
    dest: "{{ item.key }}/etc/iptables/rules.v4"
    owner: "0"
    group: "0"
    mode: "0644"
  loop: "{{ root_volume | dict2items }}"
  loop_control:
    label: "{{ item.value }}"

- name: Configure Package Preinstall File
  become: true
  blockinfile:
    path: "{{ item.key }}/root/package_preinstall"
    insertafter: "set -x"
    marker: "### ANSIBLE MANAGED BLOCK - iptables-persistent"
    block: |
      (
        echo iptables-persistent     iptables-persistent/autosave_v4 boolean false
        echo iptables-persistent     iptables-persistent/autosave_v6 boolean false
      ) | debconf-set-selections
    owner: "0"
    group: "0"
    mode: "0700"
  loop: "{{ root_volume | dict2items }}"
  loop_control:
    label: "{{ item.value }}"
